### ISSUE TITLE
Incorrect folder priority because of naming.

### ISSUE THREAD

**Issue by LaZar00** [tsunamods-codes/7th-Heaven#102]
I have been doing some tests. I use my Models Fusion mod which includes Field/Battle/World models, normally with al the files needed to create the model. I decided to add Ninostyle Chibi models (IRO) v0.245 also to 7H. So, my order is:

- Ninostyle Chibis (for Field)
- Models Fusion (basically are Chaos models, for Field)
- Other mods...

Well, the thing is that it does not matter the order I put my Models Fusion in 7H, I always see the Chaos models in game. After some checking, I detected that Ninostyle Chibis has the models in the folder **"char.lgp"**, and I have the models in the folder **"char"**.

So, as the priority is by folder naming (and they are literally different), "my" folder, "char", which has higher priority (alphabetically goes before than "char.lgp"), loads its models ALWAYS first, don't matter the order the mods are in the "My Mods" tab.

I have checked this extracting Ninostyle IRO and changing its folder to "char", then it worked correctly. But of course, a modder should not depend of the folder naming, not at least for the same type of files.

Would it be possible to treat "char/char.lgp" or "battle/battle.lgp" or "world/world_us.lgp" to be of the same level?

**Comment by julianxhokaxhiu** [comment]
> Would it be possible to treat "char/char.lgp" or "battle/battle.lgp" or "world/world_us.lgp" to be of the same level?

In 7th there is no way to have "the same level" unfortunately. Something has to come first, and something has to come second. We can swap the order but logically there's no way to "flatten" the structure.

I'm not even sure how we could fix this given the highly complex structure of the code, any PR is welcome.

**Comment by LaZar00** [comment]
I think it should be change a great amount of code to make this possible and I don't know enough 7th to give some positive answer to this. I understand the complexity of doing this.

I asked this (or opened this issue) because I detected that Ninostyle Chibis were not loading (in an old .IRO version where he was using char.lgp folder). I use char folder and 7th always loaded my chars first.

I think they solved this by now. But maybe this issue can happen also with battle/world folders for another mods.

**Comment by julianxhokaxhiu** [comment]
At this point maybe as you highlighted I'd say let's fix this on Mods instead that in the code, to avoid risking breaking other things we might not predict then.

Thanks for raising this up, I'm sorry we couldn't fix it "the right way". Cheers!

**Comment by LaZar00** [comment]
As I said, the alternative would be:
"I don't know either if this is explained in documentation or not. Maybe the people would have not problems with this order if it was better explained, and it is a more easy solution. ;)"

**Comment by julianxhokaxhiu** [comment]
This is nothing we can handle on this repo though, documentation is living on the website which only a few of the Tsunamods members have access. I'd say better raise this topic on Discord.
