### ISSUE TITLE
Automated toml settings configured by mods sometimes not been reverted.

### ISSUE THREAD

**Issue by chrcoluk** [tsunamods-codes/7th-Heaven#104]
There has been some reports on 2.5 when closing cosmo memory the SFX setting is not been changed back to default.  Possibly related to the crash reporter but not confirmed as the cause.  I have observed the same issue myself twice with the 60fps setting.

**Comment by julianxhokaxhiu** [comment]
I'd assume this being fixed as I didn't receive any feedback since the commit.
