### ISSUE TITLE
Hext files are loaded regardless of conditional met or not.

### ISSUE THREAD

**Issue by wturner859** [tsunamods-codes/7th-Heaven#118]
`<Conditional Folder="testfolder" ActiveWhen="option = 1"> <RuntimeVar Var="Byte:0x913FC3" Values="01" /> </Conditional>`

Let's say in that testfolder there is a hext file and an image file.

If the condition 01 is met, both the hext file and the image will load.

If the condition is not met, the image will not load, but the hext _will_ regardless of the conditional.

**Comment by julianxhokaxhiu** [comment]
AFAIK Hext files have no conditional loading logic, they are just loaded and applied when the game is launched.

This is basically a feature request.

**Comment by wturner859** [comment]
The entire folder the hext file is in isn't supposed to be loaded at all unless the condition is met. That's why the image doesn't load. But the hext still does.

I would think this isn't intended considering this wouldn't load unless the option is 1 even though hext files exist there:

<ModFolder Folder="Folder_With_Hext_Files"  ActiveWhen="Option = 1" />

**Comment by chrcoluk** [comment]
If this is implemented it will allow some pretty cool things like automatically detecting if another mod is loaded, boom no more need for "are you using echo-s" option.
