### ISSUE TITLE
[Error] Add new Catalog

### ISSUE THREAD

**Issue by Markul91** [tsunamods-codes/7th-Heaven#140]
The error comes from other user, i cant replicate it.
It seems that when he adds a new catalog to the 7th Heaven, the program recognizes the URL, but it says that there is no data. 
The default catalogs work fines, and he can download mods from them,but not from this external catalog. The default catalogs has some difference in respect from the external?. I dont understand the error to give him a solution. He already tried with this two URL, both works for me : 
iros://Url/https$pastebin.com/raw.php?i=7hZZHA85
iros://Url/http$pastebin.com/raw.php?i=7hZZHA85

** Versions **
3.1.00

OS: Windows 11

**Screenshots**
![RD76Mwq](https://github.com/tsunamods-codes/7th-Heaven/assets/63647725/0cffe54c-f025-474b-bea6-464f98696072)
![8jGtxVd](https://github.com/tsunamods-codes/7th-Heaven/assets/63647725/5a83601f-a185-4f3b-ad01-1b0df4f6cb11)

Thanks in advance for the help.

**Comment by julianxhokaxhiu** [comment]
Works fine using `iros://Url/https$pastebin.com/raw.php?i=7hZZHA85`. There's nothing to be done here.
