### ISSUE TITLE
No mods are loading

### ISSUE THREAD

**Issue by HitByBricks** [tsunamods-codes/7th-Heaven#141]
I’ve successfully installed the app on my Steam Deck using dotaxis’s script. The game also launches successfully with the FFNx screen showing at the beginning. But no mods are loaded whatsoever. If I have a music or sound mod enabled, no sound plays whatsoever.

EDIT: Same issue on Windows 10. Both my direct folder and textures folder are empty for some reason (if that's relevant). I've gone through multiple installs with no luck.

**Comment by HitByBricks** [comment]
Same issue on Windows 10.

**Comment by julianxhokaxhiu** [comment]
I'm sorry but we do not cover Steam Deck issues over there as it's unrelated to 7th Itself. Feel free to use the Discord server to ask for help and support. Cheers!

**Comment by HitByBricks** [comment]
It also doesn't work on my Windows desktop or laptop??

**Comment by julianxhokaxhiu** [comment]
> It also doesn't work on my Windows desktop or laptop??

You're not the only user using this product :) Feel free to ask for support, it might be something specific to you and your own setup of Windows.
