### ISSUE TITLE
7th Heaven becomes unresponsive with hidden console

### ISSUE THREAD

**Issue by AnsgarTOdinson** [tsunamods-codes/7th-Heaven#142]
**Describe the bug**
If the console is set to hidden, using the combination of /launch /quit parameters to launch 7th Heaven will cause the program to become unresponsive before launching the game.

It seems to be tied specifically to both parameters being used together and only of the console if hidden.

** Versions **
Tested on both stable and canary across 2 different machines.  I even tried it with all mods disabled.

**To Reproduce**
1. Enable hidden console
2. Close 7th Heaven
3. Launch with /launch /quit parameters
4. 7th Heaven becomes unresponsive

**Expected behavior**
The proram should boot as normal, then launch FF7.  When FF7 closes, 7th heaven should close itself

![image-2](https://github.com/tsunamods-codes/7th-Heaven/assets/39252940/83376704-e5f1-4e06-b991-e472b5ef15dd)

**Comment by julianxhokaxhiu** [comment]
Hi, thanks for the report. May I ask which option did you click to accomplish the step 1 "Enable hidden console"? So I can try to replicate it here. Thank you in advance

**Comment by AnsgarTOdinson** [comment]
Under the game launcher options, "show game launcher".  Turn that off 
<img width="356" alt="image-4" src="https://github.com/tsunamods-codes/7th-Heaven/assets/39252940/1dfbeb38-5a6f-4823-bf39-57b03f89faa5">

**Comment by julianxhokaxhiu** [comment]
Look forward to the next canary :)

**Comment by AnsgarTOdinson** [comment]
Thank you!  This makes it work seamlessly with front ends like Launchbox

**Comment by julianxhokaxhiu** [comment]
Very welcome, enjoy :)
