### ISSUE TITLE
Relative library path causing all mods to not load

### ISSUE THREAD

**Issue by user18081972** [tsunamods-codes/7th-Heaven#150]
**Describe the bug**
relative paths are only partially working.
When setting the library path to for example ".\Library", the mods download and install fine, but once you start the game, it launches without any mods.

** Versions **
[ x ] Tested on latest stable version
[ ] Pre-release only bug

**To Reproduce**
1. Set path to Library to ".\Library"
2. Download a mod
3. Enable the mod
4. Launch with mods
5. Notice mod not working

**Expected behavior**
Mods 'mounting' even with relative Library path

**Screenshots**
![image](https://github.com/tsunamods-codes/7th-Heaven/assets/124319511/8732e61d-aee7-4190-97e0-df74a8a93558)

**Desktop (please complete the following information):**
 - OS: W11
 - Version: 22H2
 - Build: 22622.2284

**Additional context**
Would be nice to support relative paths, because it can make the entire FF7 game + mods install portable.

**Comment by julianxhokaxhiu** [comment]
One question: relative to what you expect the path to resolve out of curiosity?

**Comment by julianxhokaxhiu** [comment]
Which in this case might be what you don't expect, as the same path is used for two purposes:
- It is used by the 7th GUI to manage your library
- It is used by our injection library to override game files while you play it

So having a relative path won't work as it should be relative to what? 7th? or the game path?
To avoid exactly this confusion we always left an absolute path there.
