### ISSUE TITLE
Add option to turn on Auto-Run from FFNx

### ISSUE THREAD

**Issue by waffletacos** [tsunamods-codes/7th-Heaven#162]
Hello,

Request to add a slider to turn on Auto-Run in the mod manager in the Controls setting.  I know it's in the FFNx.toml and you can change it to 'true' but it would be nice to just have a On slider in the settings.  It would help people who are not comfortable editing a file directly or having to redo it if you reinstall.

Thanks

**Comment by dotaxis** [comment]
You can enable this using the Gameplay Tweaks mod in the catalog.

This is simple enough to add to 7th Heaven and previously proposed, but we felt it would cause unnecessary clutter in the UI.

**Comment by waffletacos** [comment]
Ok, I'm not sure how adding one more slider toggle would add clutter to a UI when you have plenty of space below the others.  Being forced to use another mod seems like the wrong idea.  That option isn't the same since it sets to always run instead of adjusting movement speed the farther you press the stick up.

**Comment by julianxhokaxhiu** [comment]
Fixed by https://github.com/tsunamods-codes/7th-Heaven/commit/12e8f5f4122367562099901202426e9c25d16864
