### ISSUE TITLE
Partially French UI

### ISSUE THREAD

**Issue by mewkia** [tsunamods-codes/7th-Heaven#178]
**Describe the bug**
Parts of the UI in the game are in French instead of English when launched from 7th Heaven.

** Versions **
[x] Tested on latest stable version
[ ] Pre-release only bug

**To Reproduce**
1. Play the game in English, pay attention to text (particularly for locations, battle menus, enemy names, and enemy attacks).

**Expected behavior**
Display the English names instead of French.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version: [22H2]
 - Build: [22621.3007]

**Additional context**
Converting the exe did not help.
This issue is partially remedied by the Enhanced Stock UI by Chrysalis, but that only changes the locations and battle menus. The enemy names and enemy attacks are still in French. This makes me wonder if there could be a more roundabout solution by copying the official English text into a mod to overwrite the French.

**Comment by julianxhokaxhiu** [comment]
This is not a problem related to 7th, but for some reason people in Canada are facing this more often, since the game forcefully downloads in French and not in English despite you picking English on Steam. Double check your connection and/or your VPN if you're using one.
