### ISSUE TITLE
[Feature-Request] Create a flag like /noupdate to skip update checks and popups

### ISSUE THREAD

**Issue by Xarishark** [tsunamods-codes/7th-Heaven#186]
Please add a flag to skip update checks. 

As an example if you have the 7th Heaven added as a non steam game to steam to run it with a controller with the flags /LAUNCH /QUIT  but 7th heaven has an update then the front window will be the update popup. Instead of globally turning the update check to off it would be far better to use the flag and just don't check for updates with running the program from a shortcut with that flag. That way the game can be run with a controller and be sure to have no need for a mouse input when you are on the couch ready to play.

**Comment by julianxhokaxhiu** [comment]
Hello, sorry for the late reply but the flag is not required as it can be disabled in the settings as per screenshot below:
![Untitled](https://github.com/user-attachments/assets/733a382d-a80d-46be-b1c2-2c9f0c108d28)

Hope this helps, cheers!
