### ISSUE TITLE
Fullscreen + Speed Hack does not work

### ISSUE THREAD

**Issue by john-s3319550** [tsunamods-codes/7th-Heaven#2]
When you go fullscreen the speed hack only works in battles and even then it seems to throttle at 2.0. Outside of battles there is no change in speed.

**Comment by wturner859** [comment]
I can't reproduce this. Are you using Vsync by chance?

**Comment by john-s3319550** [comment]
No, I've tried changing numerous things too such as the driver etc. Some things break the speed hack entirely, the best I'm able to achieve is windowed mode with a speed hack Max of x4. But in full screen it never works. I couldn't tell you but old versions of 7th heaven and the tsunamods custom install worked for fullscreen. I love tsunamods custom install but there is a few mods I just gotta have from 7th heaven.

**Comment by wturner859** [comment]
wait. are you trying to use the old installable speed hack?... it's built into 7h now.

**Comment by john-s3319550** [comment]
I'm using the speed hack inside 7th heaven.

I didn't mention it but the fmv skips don't work either but installed a mod that does the same thing and it works.

Everything is updated as best I can.

**Comment by julianxhokaxhiu** [comment]
Sorry but this issue is not relevant to 7th. The speedhack is now part of FFNx and if you have issues related to a specific mod providing the very same feature, feel free to approach the relative author on the given support channels. Cheers!

**Comment by julianxhokaxhiu** [comment]
So regarding your issue @john-s3319550 have you tried disabling vsync? Also which GPU are you using? If you're on Intel GPUs, there's a known issue in their driver that caps your FPS to your monitors Hz so it can't go beyond. This limit is in place for DirectX 11/12, but NOT for OpenGL/Vulkan. Therefore feel free to use one of the two that hasn't this limit and let us know how it works.

Just to confirm that again, this is NOT a 7th issue NOR an FFNx issue. This is something that could have been discussed in Discord as is plain support for your own system.

Cheers.

**Comment by lukahn** [comment]
I had the same issue. Using DirectX 11 (even with 60FPS mod) instead of Vulcan was the fix for me (on Steam Deck).
