### ISSUE TITLE
Exception Error when running from first time 7th Heaven (canary 2.3.1.82)

### ISSUE THREAD

**Issue by LaZar00** [tsunamods-codes/7th-Heaven#35]
I have decided to do a clean install of FF7 and FFNx+7th (canaries). I'm using Windows 10 x64, as Admin.

After downloading canary 2.3.1.82 of 7H, I unzip the file to C:\Games\7th Heaven. When I try to run it, I get an exception error.
I have installed Final Fantasy VII, PC '98 spanish version on C:\Games\Final Fantasy VII before unpacking 7H to the previous mentioned folder.

I leave the applog of 7H. It seems that does not create the theme.xml, settings.xml, catalog.xml, library.xml or version.xml files in 7thWorkshop folder.

[applog.txt](https://github.com/tsunamods-codes/7th-Heaven/files/6801092/applog.txt)

**Comment by julianxhokaxhiu** [comment]
I'll fix this once #36 is merged.

**Comment by barkermn01** [comment]
@julianxhokaxhiu do you know how this is possible?

**Comment by julianxhokaxhiu** [comment]
> 
> 
> @julianxhokaxhiu do you know how this is possible?

Where there's no installation path set ( fresh install, no ff7 detected ) then this might happen. I have an idea how to fix this as we have a unique class in the entire codebase now to handle the FFNx Configuration, so I don't need to initialize a global `Sys` object to hold the path to the FFNx.toml file.

**Comment by LaZar00** [comment]
I don't know if this will help, but you can get the FF7.EXE path from registry when PC98 version is installed, and I think this works for any PC98 localized version.
![imagen](https://user-images.githubusercontent.com/46090031/125604363-3123b09f-0a2a-4938-8f8a-362901153b00.png)

**Comment by barkermn01** [comment]
The detection uses the registry as part of its detection but I don't think it's the copy from the WOW6432 node, however, I'm not even sure how that key got installed there FF7 predates 64Bit windows by quite some time, so might be some windows trickery happening on entry of that record that might not be happening on 7th heaven due to it being compiled as x86_32 (the 32 bit on 64-bit assembly type), will need looking into. might be the detection needs another key path to check for the game.

**Comment by LaZar00** [comment]
AFAIK, from W8.1 I think, when installing old Windows apps (WinXP, 2000, etc...) 32bits, the registry data that the installers put in Windows, do it in WOW6432Node entry. So, it is normal it is in this entry.

**Comment by barkermn01** [comment]
`apply patch 1.02 Spanish` ok, EU disk installer i had when this released, asked you to select a language, what copy of the disks do you have? maybe different versions of the disk installer at play here...

**Comment by julianxhokaxhiu** [comment]
> The detection system uses the registry as part of its detection but I don't think it's the copy from the WOW6432 node, however, I'm not even sure how that key got installed there FF7 predates 64Bit windows by quite some time, so might be some windows trickery happening on entry of that record that might not be happening on 7th heaven due to it being compiled as x86_32 (the 32 bit on 64-bit assembly type), will need looking into. might be the detection needs another key path to check for the game.

That's exactly the case. I remember I had this patched in 7th 1.5 long time ago, but probably the patch never mad its place on this version. This might be the real solution to this issue. I'll look into it this evening.

**Comment by LaZar00** [comment]
> 
> 
> `apply patch 1.02 Spanish` ok, EU disk installer (from the UK) i had when this released, asked you to select a language, what copy of the disks do you have? maybe different versions of the disk installer at play here...

No, no, spanish PC98 retail disk does not asks for any language. It installs directly (with spanish installer). Even it has a problem (if you have installed a previous version of FF7 PC98), that it gives an Error 432 the installer. You must delete from Windows directory the files IsUn040a.exe and IsUninst.exe (if not you can not install/reinstall it):
![imagen](https://user-images.githubusercontent.com/46090031/125612125-b9b7dffb-352c-4f3b-8d0d-9c081a9935ca.png)

FYI, even the auto-converter works well. ;)

**Comment by julianxhokaxhiu** [comment]
Registry keys detection works fine and nothing has to be done. The crash is completely unrelated and it was introduced by #33 when I mistakenly thought I could use one property on init. This has now been fixed in #37.
