### ISSUE TITLE
Sorry but this issue is not relevant to 7th. The speedhack is now part of FFNx and if you have issues related to a specific mod providing the very same feature, feel free to approach the relative author on the given support channels. Cheers!

### ISSUE THREAD

**Issue by john-s3319550** [tsunamods-codes/7th-Heaven#4]
Sorry but this issue is not relevant to 7th. The speedhack is now part of FFNx and if you have issues related to a specific mod providing the very same feature, feel free to approach the relative author on the given support channels. Cheers!

_Originally posted by @julianxhokaxhiu in https://github.com/tsunamods-codes/7th-Heaven/issues/2#issuecomment-841796810_

I didn't say what you thought. The issues are in 7th heaven. I have multiple issues, one of them had a successful work around by using a mod was all I was saying. I have no issues with the mod, so maybe you can talk to the mod creator and ask them for their code so it fixes your issue! I am telling you about it. So Fix it or don't fix it but please don't cut me off because you misread something.

**Comment by julianxhokaxhiu** [comment]
Please avoid opening such meaningless issues and perhaps approach us on Discord which would be more efficient. Let's continue on #1
