### ISSUE TITLE
Install process extracting 7zip is single threaded

### ISSUE THREAD

**Issue by chrcoluk** [tsunamods-codes/7th-Heaven#46]
The install part of downloading mods, is slow which can lead to users getting confused its hung and maybe they close 7h whilst its still extracting.

I suggest making this multithreaded, preferably by detecting number of threads in system and using all of them or if not at least make it 4 threads.

This only affects 7zip compressed mods not mods distributed in iro format.

**Comment by barkermn01** [comment]
IRO format mods are not expected to the file system unless the user explicitly does it, however, I'm not sure if LZMA that 7zip uses supports multi-threaded extraction because even 7zip application does not do multi-threaded extraction, however, it might be worth looking at updating the progress bar for downloading so it changes to extracting and shows a progress bar.

**Comment by chrcoluk** [comment]
I am not at home right now to check, but I am fairly sure the 7zip app (at least on windows) is multi thread extraction, I can extract even really big mods in under 10 seconds using the 7zip application, but its in many multiples slower when downloading 7zipped mods.

**Comment by barkermn01** [comment]
@chrcoluk is there any update to your investigation?

**Comment by chrcoluk** [comment]
I just tested and 7zip extraction on cetra mains used all of my cpu threads, so yes its multi threaded.  The file is LZMA2 format.

I tried to find documentation to see if LZMA is thread restricted on decompression, but couldnt ifnd anything although did find this article which suggests its not restricted.  I will recompress cetra with LZMA and test that as well.

https://www.7-cpu.com

**Comment by barkermn01** [comment]
So we're using the LZMA implementation from a NuGet Package, I can't remember which one currently but will look when I get home tonight, so if you know of another implementation library that we can use that does do MultiThreaded LZMA we can look at switching over to it.

**Comment by barkermn01** [comment]
So we're using,

`SharpCompress.Compressors.LZMA.LzmaStream`

And the problem is IRO's use their own LZMA stream system, and this means it's not LZMA2 that 7Zip uses, you can read more details about why we can't do this here,

https://github.com/adamhathcock/sharpcompress/issues/190
