### ISSUE TITLE
Auto size detection for mods

### ISSUE THREAD

**Issue by chrcoluk** [tsunamods-codes/7th-Heaven#47]
Usually when downloading with a web browser, it knows the size of the file it is downloading so can do resume correctly and a progress bar.

I think there needs to be a change within 7h to do the same.

Currently we have to manually put the size of the mod in the catalog, this has to be manually updated if a mod updated changes the size.

If the size is wrong on the catalog it can break resuming downloads or make downloads hang.  Generating 416 errors on the web server.

I did disable range detection on the web server but this ended up breaking "all" resumes so its now back on and the catalog sizes have been updated for every mod, however I think the way forward is to implement a new size detection process, whether this is hints sent from the server on downloads or another auto detection method.

Once this is done we can repurpose the size shown on the catalog page to be a cosmetic install size for the end user to know how much space they need instead of using that value for the download code.

**Comment by chrcoluk** [comment]
Some additional info.

7thheaven when downloading mods seems to treat every file as a resume even when the starting point is 0 bytes, the response code is 206 when succeeding but any downloads from a web browser are code 200.

**Comment by barkermn01** [comment]
So it should be possible to use the server headers on connection to know how big a file is if the server sends that, however, because the download manager uses multiple methods it might not be so simple GDrive and Mega are Via API's verses raw HTTP address downloads.

**Comment by chrcoluk** [comment]
There is a header that is returned for every request so yep should be possible to use the headers.

Should be the "content-length" header.

On a normal download (web browsing etc.) the client doesnt request a range, instead it just requests the file, and that header is sent to client so it knows the size.  7th heaven is "always" requesting a range of bytes for every download, which seems to be causing problems for some people.

I dont know if this change would even affect google drive or megadrive as the api's are different, but of course we should test to see if those are impacted.

Originally 7h 1.5 didnt even support resuming downloads, and I think this was the same for 2.0 as well, so that code if you can find it probably does the same as a web browser and I guess the resume support was added for every download instead of just when someone clicks the resume button.

**Comment by barkermn01** [comment]
yeah it should be but it can also be missing if it's vai a download script that does not send it and not sure what we can do about that, other than have a file hash verification

**Comment by barkermn01** [comment]
Ok, im going to kill this off for 7th heaven, and move it to prelude i think, adding this sort of fundamental rewrite to the downloader is going to be a big task due to the way the downloader is coded, so should work better with a new downloader which will be implemented into prelude.
