### ISSUE TITLE
7h randomly fails to detect compression type.

### ISSUE THREAD

**Issue by chrcoluk** [tsunamods-codes/7th-Heaven#48]
This is likely a cause of random reports of download failure.

I was able to reproduce the fail to install message, when this occurs 7h has to be restarted for another attempt to be made.

Extract of 7h log below, the file downloaded fine after restarting 7h and trying again.

`19:20:12|INFO|SeventhHeavenUI.ViewModels.MainWindowViewModel|Error installing Spell Textures - The mod is queued for install.
19:20:12|ERROR|SeventhHeavenUI.ViewModels.MainWindowViewModel|System.InvalidOperationException: Cannot determine compressed stream type. Supported Archive Formats: Zip, GZip, Tar, Rar, 7Zip, LZip
   at SharpCompress.Archives.ArchiveFactory.Open(Stream stream, ReaderOptions readerOptions)
   at Iros._7th.Workshop.Install.InstallModProcedure.ProcessDownload(Object state)`

**Comment by Sebanisu** [comment]
The mod file isn't corrupt? That's my first guess mod archive failed to finish downloading resulting in a corrupt file. Maybe should offer to redownload it? If that isn't it maybe the file isn't being loaded correctly.

**Comment by chrcoluk** [comment]
I will check if a corrupt file exists if I see it happen again, the error did appear immediately when I seen it.

**Comment by barkermn01** [comment]
>I will check if a corrupt file exists if I see it happen again, the error did appear immediately when I seen it.

Is there a reliable way to check? does the catalogue store a hash or file size for the download we can use to verify?

**Comment by chrcoluk** [comment]
It stores the file size but it needs to be manually entered by the catalog maintainer.

I wouldnt be against hash checking.

At the time I was using the latest catalog url, and sadly I cannot remember which mod caused the compression error.

**Comment by chrcoluk** [comment]
There has been fixes added to fix download problems, so closing this, will reopen if proves to be a problem in the future.
