### ISSUE TITLE
FFNx.toml not found

### ISSUE THREAD

**Issue by Reaper-X55** [tsunamods-codes/7th-Heaven#50]
**Describe the bug**
I'm not exactly sure what the bug is, but for some reason when I try to open up the Game Driver tab on 7th Heaven, I get an error telling me that 7th Heaven cannot find the FFNx.toml. I've run the game several times using the play button on the top left, but no matter when I click the game driver it still can't seem to find it. When playing the game, 7th Heaven seems to be trying to install FFNx with an indefinite download time. 
I'm able to get to the Continue or New Game Screen, but when hitting New Game I then get transferred to a black screen.
EDIT: Okay, minor update, no longer getting a black screen, but it is telling me to insert a disk.

It also seems that anytime I pull away to the Game screen to see if it's running properly, all my other screens get reduced in size as if the resolution is being put to 4k or something.

** Versions **
2.3.1

**Comment by barkermn01** [comment]
@Reaper-X55 did the above fix your issue?
