### ISSUE TITLE
7th Heaven always changes external_music_path and external_music_ext

### ISSUE THREAD

**Issue by malvarenga123** [tsunamods-codes/7th-Heaven#51]
**Describe the bug**
It's not possible to use myst6re's psf pack with 7th Heaven because it keeps changing external_music_path and external_music_ext to "music/vgmstream" and "ogg", respectively.

**Versions**
[X] Tested on latest stable version (2.3.3.0)
[ ] Pre-release only bug

**To Reproduce**
Run the game (I'm using minimal validation) with mods (no sound mods) and check the newly created FFNx.toml, while the game is running.

**Expected behavior**
7th Heaven should not change user-defined values in FFNx.toml.
Another option is to make 7th Heaven NOT try to write a new FFNx.tom if the original is set to read-only. Right now it just refuses to launch the game if it can't write to the file.

**Desktop (please complete the following information):**
 - OS: Windows 7 x64

**Comment by barkermn01** [comment]
@malvarenga123 this is an issue with the 7th Heaven FFNx connector as written by @julianxhokaxhiu, you may wish to speak to them to ask if they can submit a pull request to fix it, if not I'm going to have to dig through it but I'm making no promises, and i thought it did not write a new toml if there was one and there were no changes

**Comment by julianxhokaxhiu** [comment]
This PR is exactly tackling this issue AFAIK: https://github.com/tsunamods-codes/7th-Heaven/pull/45

And is done by @myst6re himself, being the author of its own mod, I think he faced the issue personally and did try to fix the behavior. Not sure though how far it was tested. Maybe you need to use the IRO instead of manually installing it?

**Comment by myst6re** [comment]
> This PR is exactly tackling this issue AFAIK: #45

Yeah like you said this PR was done to resolve this specific issue.

I added my IRO in the Qhimm topic, not tested with the official stable version.
Please note that you will still have issues with the hebios file, you need to put it manually in the correct path.

https://forums.qhimm.com/index.php?topic=19967.msg278127#msg278127

**Comment by barkermn01** [comment]
So this change is merged in the merge was done on the 11th Oct, installer under releases was created 25th of Oct, please download 2.3.3 setup, just on this note @julianxhokaxhiu has the latest FFNx been tested with 7th heaven or should I get some people to test it, and package it into a new installer version?

**Comment by julianxhokaxhiu** [comment]
> So this change is merged in, the merge was done on the 11th Oct, installer under releases was created 25th of Oct, please download 2.3.3 setup, just on this note @julianxhokaxhiu has the latest FFNx been tested with 7th heaven or should I get some people to test it, and package it into a new installer version?

No idea, consider using the latest stable please. Canary is fully WIP.

**Comment by barkermn01** [comment]
@julianxhokaxhiu we're not using canary it using 1.9.x something just before the steam achievements update, will update in next release and close this as the issue has been merged fixed in #52
