### ISSUE TITLE
Unable to select install folder

### ISSUE THREAD

**Issue by DavidBabel** [tsunamods-codes/7th-Heaven#54]
**Describe the bug**
As you can see here : 
![image](https://user-images.githubusercontent.com/5599375/148447050-59213072-f1be-4113-826c-00bb75649109.png)

** Versions **
[x] Tested on latest stable version
[ ] Pre-release only bug

**To Reproduce**
1. I installed FF7 on E:/ first
2. I installed 7th Heaven
3. I unstalled My FF7 cause it did not work
4. I uninstalled 7th Heaven
5. Reinstalled official steam FF7 version in C:/
6. Launch setup of 7th Heaven

**Expected behavior**
The "browse" button for FF7 path does not work and then : 
![image](https://user-images.githubusercontent.com/5599375/148446927-333f8f91-c09c-4ce7-bad7-98d79dbf9764.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**

**Comment by barkermn01** [comment]
So this is because the Steam version has been detected, but then steam does not know where the game is located, you should not move a steam game without using steam to move it, so because of that I think the browse button state is confusing, i will look into fixing it.

**Comment by barkermn01** [comment]
Unable to fix this duty to Steam's stupidity if you have this issue we recommend uninstalling 7th heaven and then reinstalling it.

**Comment by OwenPattison** [comment]
I'm facing exactly the same issue, if the intention is to not resolve the issue - you probably should remove the browse button that doesn't work, it's very misleading.
