### ISSUE TITLE
incorrect messages in "Load Order Incompatible" notification.

### ISSUE THREAD

**Issue by wturner859** [tsunamods-codes/7th-Heaven#58]
When load order is constrained via mod.xml and loaded in the wrong order, a message should display with the strings according to StringResources.xaml:

    <system:String x:Key="TheFollowingModsWillNotWorkProperlyInTheCurrentOrder">The following mods will not work properly in the current order. Do you want to continue anyway?</system:String>
    <system:String x:Key="LoadOrderIncompatible">Load Order Incompatible</system:String>
    <system:String x:Key="ModIsMeantToComeBelowModInTheLoadOrder">Mod {0} is meant to come BELOW mod {1} in the load order</system:String>
    <system:String x:Key="ModIsMeantToComeAboveModInTheLoadOrder">Mod {0} is meant to come ABOVE mod {1} in the load order</system:String>

However, what actually displays is : 

    <system:String x:Key="TheFollowingModsWillNotWorkProperlyInTheCurrentOrder">The following mods will not work properly in the current order. Do you want to continue anyway?</system:String>
    <system:String x:Key="LoadOrderIncompatible">Load Order Incompatible</system:String>
    <system:String x:Key="ModIsNotCompatibleWithYouWillNeedToDisableIt">Mod {0} is not compatible with {1}. You will need to disable it.</system:String>

**Comment by wturner859** [comment]
This results in:
![image](https://user-images.githubusercontent.com/4468996/151661000-a574b689-6511-44a2-87d4-e6f5aab7185d.png)

**Comment by barkermn01** [comment]
This has been fixed in #65
