### ISSUE TITLE
[Feature Request] Add Carlucci Ace Catalog to the system defaults

### ISSUE THREAD

**Issue by CarlucciMods** [tsunamods-codes/7th-Heaven#59]
Carlucci Ace Catalog

iros://Url/http$chris.7thheaven.rocks/carlucci/CarlucciAceCatalog1312022.xml
![1 31 2022](https://user-images.githubusercontent.com/31194015/151847890-169da069-6e69-4ea1-82f2-0d3d97154bdb.PNG)

**Comment by chrcoluk** [comment]
As bonez stated on the catalog repo issue, this wont be added.

**Comment by CarlucciMods** [comment]
This was the newest catalog, i removed all the black albums.  But As I said, i have to many edit to keep bothering users to fix catalog updates. besides the google link doesn't work anyway !

<?xml version="1.0"?>
<Catalog Name="Carlucci Catalog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 
 <Mods>
 
## Carlucci Mod Music Manager Beta ##
<Mod>
<ID>a02279c4-c947-44d9-84d6-4200486261d8</ID>
<Author>Carlucci Mods </Author>
<Link>https://discord.gg/y7aTwE6</Link>
<LatestVersion>
<Link>iros://Url/http$drive.google.com/file/d/1w3ObPcLg8_dwuG9mU3J7ybIabAxTFdUU</Link>
<Version>3.010</Version>
<ReleaseDate>2022-04-11</ReleaseDate>
<PreviewImage>https://raw.githubusercontent.com/carlucci9660/Mod-Music-Manager/main/CAMM2.PNG</PreviewImage>
<ReleaseNotes>Beta Release: An All in One Music Manager. Albums Selection and Shuffle are in Full working Order. Individual Tracks Selections need some looping work. My main dev has left the project due to family. +++

Upcoming Updates:
3.011 Adding New Artists Additions: Smooth Groove, The Reunion - FF7 PSX OST,  Slayer Santiago,  Feɴɪx Aʀk Aɴɢeʟes, Qhimm Mix, DisposedHeroVGM,
Ivan H_ Juan Medrano (ocremix), Rifti Beats, Cashglom, ctrlaltQQ, FamilyJulez7x w/Those Who Fight Further Mix. 

3.010 Updated Artwork. Added New Artists The Reunion - FF7 PSX OST, Qhimm Mix and E.D. Music. Thanks to Enrico for allowing us to use their music. Also a big thanks to all those who worked on his album in the modding community.

CAMS and CAMS-R have now been merged into one, "The Carlucci Mods Music Manager". We hope all the hard work made a good procduct and have hopes that one day it turns into the full audio manager. 

2/16/2022 Updates from Former CAMS-R:


3.582 Added Single Tracks Bonus Contacnt: G. Scorpion
3.581 Corrected Mislables in 3 metal tracks.
3.580 Renamed all tracks with [artist name_location]
3.574 Updated Shuffle order; New .toml scripter run
3.573 Boss Battle Edits: Updated Looping and Increased/normalized track volume to -1.0 db.
3.572 Added Complete Artist List.ods inside cams-r root folder.
3.571 Description Update.
3.570 Updated Mod with Animated Logo.
3.560 Victory Music Edits: Updated Looping and Increased/normalized track volume to -1.0 db.
3.550 New artwork for Selection UI.
3.540 Changed OST Style Genre to Arranged Genre.
3.530 Battle Music Edits: Updated Looping and Increased/normalized track volume to -1.0 db.
3.520 Fixed: Issue #002 Vincent Bravo and Girlz Melon don't preview in victory fanfare.
3.520 Removed: Issue #003 Mattias Haggstrom Gerdt preview of thoses who fight further the button changes but no preview audio.

This mod is in Beta while being tested.</ReleaseNotes>
<DownloadSize>3932060</DownloadSize>
</LatestVersion>
<MetaVersion>0</MetaVersion>
<Name>Carlucci Ace Music Manager Beta</Name>
<Category>Media</Category>
<Description></Description>

<Tags>
<string>Media</string>
<string>Music</string>
</Tags>
</Mod> 

 </Mods>
</Catalog>
