### ISSUE TITLE
Password Protected .7z mods

### ISSUE THREAD

**Issue by carlucci9660** [tsunamods-codes/7th-Heaven#60]
Just an idea for those wanting to lock mods for whatever reasons for those who only have the key to access it.....ex: paid patreons etc 

once the 7z file is created with password on the local pc, 7th heaven downloads it or prompts for password to those that have it already.

**Comment by barkermn01** [comment]
This is currently not possible Blocked by https://github.com/adamhathcock/sharpcompress/issues/208

**Comment by chrcoluk** [comment]
7th Heaven is an open system by nature of its design, and as above its not possible anyway.
