### ISSUE TITLE
7th Heaven not clearing download state.

### ISSUE THREAD

**Issue by chrcoluk** [tsunamods-codes/7th-Heaven#61]
Version 2.3.3.0

As requested.

If download a invalid file e.g. does not exist error 404, and then try again, it will state download is already in progress, restarting 7h fixes it.

In addition if downloading and abort via the cross button, the same problem occurs, also clears upon restarting 7h.

**Comment by barkermn01** [comment]
Thanks for creating this as requested i will investigate and try to fix

**Comment by barkermn01** [comment]
This has been fixed in #64
