### ISSUE TITLE
[Feature-Request] add "lighting" to the additional folders to monitor

### ISSUE THREAD

**Issue by CosmosXIII** [tsunamods-codes/7th-Heaven#67]
I would like to request adding "lighting" by default to the additional folders to monitor so that we can use data from this directory from FFNx.
This folder contains the lighting config file as well as data such as environment maps that would be included in an IRO.
Right now it needs to be added manually so having it there by default would be useful.

Thanks, and let me know if there is need to clarify anything.

![image](https://user-images.githubusercontent.com/82299148/152676640-bc819dcc-d892-4b91-bd16-c55d49bf7683.png)

**Comment by barkermn01** [comment]
Has been committed.
