### ISSUE TITLE
FFNx.toml does not revert back when FF7 crashes/closes and/or when mod that changes it is disabled.

### ISSUE THREAD

**Issue by tangtang95** [tsunamods-codes/7th-Heaven#68]
When FF7 crashes while using an IRO mod that modifies FFNx.toml configs, the previous FFNx.toml (before modifying it) is not brought back. So the FFNx config changes done by the IRO persists after the game crashes. I have tested in on 7th heaven 2.3.1.101 but I suppose this is not fixed in 2.3.3

**Comment by barkermn01** [comment]
Sorry, but i'm slightly confused by,

> I have tested in on 7th heaven 2.3.1.101 but I suppose this is not fixed in 2.3.3

Have you tested in 2.3.3? if not please could you. also, 2.3.1.101, was an old test client and should definitely not be used anymore

**Comment by tangtang95** [comment]
Couldn't replicate the bug even in the old version. For now I don't know how to replicate it.

**Comment by barkermn01** [comment]
![image](https://user-images.githubusercontent.com/37368/154069537-bf88bf86-4971-46aa-8b77-44c5cb748f24.png)

**Comment by barkermn01** [comment]
![image](https://user-images.githubusercontent.com/37368/154069945-4d42dd25-d1f3-47ae-9855-7f9931112972.png)

Code that is not working is https://github.com/tsunamods-codes/7th-Heaven/blob/master/SeventhHeavenUI/Classes/GameLauncher.cs#L833

**Comment by chrcoluk** [comment]
This bug is as Bonez described, enabling a mod such as 60fps that alters a FFNx setting, the setting is not (always?) reverting back to what it was before when the game is shut down, crash or not.

**Comment by chrcoluk** [comment]
This has been fixed in build 2.3.3.11
