### ISSUE TITLE
[Bug] Can't launch the game without Code 5 fix

### ISSUE THREAD

**Issue by Urbanhack86** [tsunamods-codes/7th-Heaven#7]
hi, with 2.3.1.19 the game wont launch after run it with any mod. i try ESUI mod but got an error in the cmd windows. if i disable mods the game run ok.

**Comment by julianxhokaxhiu** [comment]
Try with the latest canary and enable the code 5 fix option.

**Comment by barkermn01** [comment]
We might have an update that will fix this https://github.com/tsunamods-codes/7th-Heaven/pull/17 has fixed a problem that was causing code 5 fix to be needed a lot, so when a new canary comes out that might have been fixed if you can test and let us know @Urbanhack86 would be wonderful

**Comment by julianxhokaxhiu** [comment]
I can confirm the patch worked for me too ( I was using the Code 5 Fix as it didn't work without recently ). Thank you @barkermn01

**Comment by julianxhokaxhiu** [comment]
No complains, good to go.
