### ISSUE TITLE
Increase in Limitation Request

### ISSUE THREAD

**Issue by carlucci9660** [tsunamods-codes/7th-Heaven#71]
21:07:03|WARN|SeventhHeavenUI.ViewModels.CatalogViewModel|preview image greater than 3MB, cancelling download

Can we bump it up to 5MB....scaling down logos makes it really hard to see text. And the dithering is very bad.
![CAMS-RB (2)](https://user-images.githubusercontent.com/31194015/153326037-1b22bb37-96c0-4c82-9235-3dee3f3556cc.gif)
 

thank you for your hard work

**Comment by barkermn01** [comment]
Options have been added to allow users to select a different size, #73
