### ISSUE TITLE
Commit e555a60 (MB vs MiB)

### ISSUE THREAD

**Issue by malvarenga123** [tsunamods-codes/7th-Heaven#74]
I think it's reversed. MB = 1000^2 and MiB = 1024^2
https://en.wikipedia.org/wiki/Byte#Multiple-byte_units

**Comment by barkermn01** [comment]
How in the world has this ended up reversed? Byte quite literally means the power of 8...

So which is correct Memory or HDD's now?

**Comment by malvarenga123** [comment]
> I was using the metrics from the app because i thought it was the other way around, but I know i hate the system because HDD manufacturers are Arses, they should never have been saying GB for 1000

This has been an issue for decades. One thing though, bit is never used, only bytes. So it never mattered if 1 byte is 8 bits. Technically the value is correct (a 8 GB  thumbrive does have 8.000.000.000 bytes). It's the OSs that have been using the wrong prefixes all these years, not disk manufacturers. The IS prefixes have existed way before computers were a thing, only god knows why someone decided to use the same prefixes with different values. Binary prefixes were supposed to fix this, sadly they never really caught on.

IMO, if you want to clear all doubt, you should replace instances of KB, MB and GB to KiB, MiB and GiB, in 7th Heaven.

**Comment by barkermn01** [comment]
> It's the OSs that have been using the wrong prefixes all these years, not disk manufacturers.

This is wrong OSes use the Older Standard for [JEDEC](https://en.wikipedia.org/wiki/JEDEC), IEC should not have created an alternative standard in 2008 after the JEDEC standard in 1990's the only reason to do that was to cause competition as it defies the point of having standards...

All Major OS came long before 2008, the IEC going against the convention presented to users for many years is a failure of a standards organisation, how can they say that everything people have been exposed to for 20 years is incorrect in favour of their view. that quite literally defies the point of standard...

**Comment by malvarenga123** [comment]
Are you sure? The JEDEC standard is from 2002 according to their page: https://www.jedec.org/document_search/field_doc_type/148
The SI prefixes were defined in 1960, weren't they?

> The point should have been if your using metrics you use lower case, E.G (mm, cm, m, km), (ml, cl, lt), (mg, g, kg) they should always use lower case, KB, MB, GB, TB, are all uppercase

All units above kilo (k) are in uppercase according to the SI. The lowercase units have a different meaning (mili, deci, centi, etc) and, as you said, b means bit and B means byte. The fact remains that there was no reason to "overload" units even if you were using a different base. You can see that this was going to be an issue back in 1968:
https://en.wikipedia.org/wiki/Binary_prefix#Early_suggestions

While early computer scientists typically used k to mean 1000, some recognized the convenience that would result from working with multiples of 1024 and the confusion that resulted from using the same prefixes for two different meanings.

Several proposals for unique binary prefixes were made in 1968. Donald Morrison proposed to use the Greek letter kappa ([κ](https://en.wikipedia.org/wiki/%CE%9A)) to denote 1024, κ2 to denote 1024^2, and so on. (At the time, memory size was small, and only K was in widespread use.) [Wallace Givens](https://en.wikipedia.org/wiki/Wallace_Givens) responded with a proposal to use bK as an abbreviation for 1024 and bK2 or bK^2 for 1024^2, though he noted that neither the Greek letter nor lowercase letter b would be easy to reproduce on computer printers of the day. [Bruce Alan Martin](https://en.wikipedia.org/w/index.php?title=Bruce_Alan_Martin&action=edit&redlink=1) of [Brookhaven National Laboratory](https://en.wikipedia.org/wiki/Brookhaven_National_Laboratory) further proposed that the prefixes be abandoned altogether, and the letter [B](https://en.wikipedia.org/wiki/Binary_scientific_notation) be used for base-2 exponents, similar to [E](https://en.wikipedia.org/wiki/E_notation) in [decimal scientific notation](https://en.wikipedia.org/wiki/Decimal_scientific_notation), to create shorthands like 3B20 for 3×220, a convention still used on some calculators to present binary floating point-numbers today.

None of these gained much acceptance, and capitalization of the letter K became the de facto standard for indicating a factor of 1024 instead of 1000, although this could not be extended to higher powers.

As the discrepancy between the two systems increased in the higher-order powers, more proposals for unique prefixes were made. In 1996, [Markus Kuhn](https://en.wikipedia.org/wiki/Markus_Kuhn_(computer_scientist)) proposed a system with di prefixes, like the "dikilobyte" (K₂B or K2B). [Donald Knuth](https://en.wikipedia.org/wiki/Donald_Knuth), who uses decimal notation like 1 MB = 1000 kB, expressed "astonishment" that the IEC proposal was adopted, calling them "funny-sounding" and opining that proponents were assuming "that standards are automatically adopted just because they are there." Knuth proposed that the powers of 1024 be designated as "large kilobytes" and "large megabytes" (abbreviated KKB and MMB, as "doubling the letter connotes both binary-ness and large-ness"). [Double prefixes](https://en.wikipedia.org/wiki/Metric_prefix#Double_prefixes) were already abolished from SI, however, having a multiplicative meaning ("MMB" would be equivalent to "TB"), and this proposed usage never gained any traction.

**Comment by barkermn01** [comment]
> expressed "astonishment" that the IEC proposal was adopted, calling them "funny-sounding" and opining that proponents were assuming "that standards are automatically adopted just because they are there."

This bit, not to mention co-opting another pre-existing standard... which should not be done standards are the to alleviate confusion not create more :D

**Comment by malvarenga123** [comment]
I think I read that Apple recently changed MacOS to use SI prefixes correctly (1000^n) but I don't have a Mac to check. If Microsoft followed the same trend, it would be better in the long-run IMO. This mess has been dragged out long enough.
