### ISSUE TITLE
[Improvement] Reset settings to default after any FFNx update

### ISSUE THREAD

**Issue by Tsunamods** [tsunamods-codes/7th-Heaven#8]
When updating FFNx inside 7H, instead of the popup saying "Please reset to defaults".
Have it open the General Settings window itself, auto reset them to defaults then pop up saying "Please reconfig these settings".

This will greatly help average users.

**Comment by julianxhokaxhiu** [comment]
One way of accomplishing this is by moving the entire config management code from the Game Driver window class to a generic one and then make that class usable by all the places where it is needed. This might also unlock potentially new scenarios. I'll take this item as I know what to patch already.

**Comment by julianxhokaxhiu** [comment]
Fixed by #33
