### ISSUE TITLE
Incorrect logic in commit regarding MB/MiB

### ISSUE THREAD

**Issue by Dizzy611** [tsunamods-codes/7th-Heaven#81]
**Describe the bug**
Backwards logic in commit https://github.com/tsunamods-codes/7th-Heaven/commit/4b42728f981924c1c69bd8cf37106ec321b5dcf2

MB stands for "Megabyte", which is a power of 10, MiB stands for "Mebibyte" which is a power of 2. That is to say, the original code was correct and the person who made this change was incorrect.

** Versions **
[ ] Tested on latest stable version
[ ] Pre-release only bug

**To Reproduce**
Read the commit history and then read a wikipedia article about mebibytes.

**Expected behavior**
People not asserting things that are demonstrably false.
https://en.wikipedia.org/wiki/Byte#Multiple-byte_units

**Comment by chrcoluk** [comment]
Thanks, will be fixed in a future build.

**Comment by barkermn01** [comment]
This was highlighted and corrected in the now missing commit f12f90f987b3fc09c40648182695a2b274b11513

From https://github.com/tsunamods-codes/7th-Heaven/issues/74

**Comment by julianxhokaxhiu** [comment]
Thanks for pointing this out. I missed that commit as I couldn't merge it clean, so I refactored it a bit to resemble the original one.

Cheers!
