### ISSUE TITLE
(Suggestion) Allow to set a custom resolution when Windows Mode Windowed is selected

### ISSUE THREAD

**Issue by chrcoluk** [tsunamods-codes/7th-Heaven#86]
Seems this resolution is not available for users who own a display capable of using it such as 4k displays, this is the closest integer resolution to 4k, the other two been 640x480 and 1280x960 which are available.

**Comment by julianxhokaxhiu** [comment]
I think instead of adding an arbitrary value to the dropdown we should probably tackle this by allowing users to put a custom resolution, this would be much more appropriate. Right now we obtain the available "fullscreen" resolutions of the monitor, but windowed is not considered.
