### ISSUE TITLE
Help text buttons dont display correctly in Spanish Language

### ISSUE THREAD

**Issue by Markul91** [tsunamods-codes/7th-Heaven#95]
**Describe the bug**
The menu buttons of "Help" ,dont display  correctly(no text) in spanish language.

** Versions **
Error in V2.5.0.0 Version

**To Reproduce**
Change language of 7th heaven to Spanish languageand select the "Help "button

**Expected behavior**

**Screenshots**
![Captura2](https://user-images.githubusercontent.com/63647725/174452430-5c0a8ef1-d700-44d3-881e-4604c85db4b2.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by julianxhokaxhiu** [comment]
Please update to the latest canary or the next stable release, when it will be announced.
